# =======================================================
# 작성자(Author) 정보
# =======================================================
author:
  name: "성진 (Sungjin)"
  avatar: "https://turbulentflux.com/wp-content/uploads/2020/09/20200831_Data_Information_Knowledge.png"
  bio: "매일 코딩하는 꿈을 꾸는 청년(DW Academy)
  url: "https://sungjin-dev.github.io"
  location: "South Korea"
  links:
    - label: "tjdwlsl8888@gmail.com" 
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:tjdwlsl8888@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sungjin-dev"

timezone: "Asia/Seoul" # 한국 시간대 설정 (포스팅 시간이 정확해집니다)

# =======================================================
# 테마 및 플러그인 설정
# =======================================================
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-include-cache
  - jekyll-paginate

search: true

# =======================================================
# 마크다운 렌더링 설정 
# =======================================================
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false


# =======================================================
# 블로그 글 기본 설정 (오른쪽 목차 메뉴 자동 고정)
# =======================================================
defaults:
  - scope:
      path: ""       # 블로그의 모든 경로에 있는
      type: "posts"
    values:
      layout: "single"  # 포스트 기본 레이아웃
      toc: true         # 목차(TOC) 활성화
      toc_sticky: true  # 스크롤 시 목차 오른쪽 고정
      sidebar:         
        nav: "sidebar_category"
